name: Purge CloudFlare cache
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_TOKEN }}
